library(data.table)
DT_train <- as.data.table(read.csv('./data/train.csv'))
DT_gender_model <- as.data.table(read.csv('./data/gendermodel.csv'))
DT_gender_class_model <- as.data.table(read.csv('./data/genderclassmodel.csv'))
DT_test <- as.data.table(read.csv('./data/test.csv'))
